// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqceykdsjitfprnldrsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY2V5a2Rzaml0ZnBybmxkcnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTE1MDIsImV4cCI6MjA1NTY2NzUwMn0.E1CTDMqCl5uJIzmrx1t2Sme3lAC1KXSpXS3elSXizvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);